# Use a Python base image
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y nmap

COPY . .

# Define a CMD to be informative (can be overridden during execution)
# CMD ["echo", "Application image ready"]
CMD ["python", "arkyide.py"]